name: Github 2 Dockerhub 2 Slack
on:
  release:
    types: [published]
  

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the code from github repo
        uses: actions/checkout@v3
      - 
        name: Login to hub.docker.io 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3 
        with:
          push: true
          tags: xietingting90/randnum:${{ github.ref_name }}

      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: XIE TINGTING \n Matriculation: A0249501J \n Email: xietingting-1990@hotmail.com \n Repo: ${{ github.repositoryUrl }} \n Image name:  xietingting90/randnum:${{ github.ref_name }} \n Image URL: https://hub.docker.com/repository/docker/xietingting90/randnum"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK