name: Github 2 Dockerhub 2 Slack
on:
  push:
    # types: [published]
    # tag:
    # - v1.*

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the code from github repo
        uses: actions/checkout@v3
      - 
        name: Login to hub.docker.io 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: xietingting90/randnum:v0.3

      # https://github.com/marketplace/actions/slack-webhook
      # - name: Post message on slack
      #   uses: bluenovaio/action-slack@main 
      #   with:
      #     username: "Somik"
      #     icon_emoji: ":robot_face:"
      #     text:  "${{secrets.SLACK_MSG}} \nRepo: ${{ github.repositoryUrl }}\nImage name: ${{ secrets.DOCKERHUB_USERNAME }}/randimg:${{github.ref_name}}\nImage url: https://hub.docker.com/repository/docker/somik123/randimg"
      #     webhook_url: ${{ secrets.SLACK_WEBHOOK }}